#!/bin/sh

echo "// generated by build_site_specific.sh, do not modify!"
echo
echo "const table = [];"
echo

for lsf in site_specific/*.ls; do
    base=$(basename "$lsf")
    echo "import $base from './$lsf';"
    echo "table.push($base);"
    echo
done

echo "export default table;"
